# Generated by Django 2.2 on 2019-04-23 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vaspinout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('catagory', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('compare_id', models.IntegerField(null=True)),
                ('incar', models.TextField(null=True)),
                ('kpoints', models.TextField(null=True)),
                ('poscar', models.TextField(null=True)),
                ('contcar', models.TextField(null=True)),
                ('enginval', models.TextField(null=True)),
                ('oszicar', models.TextField(null=True)),
                ('doscar', models.TextField(null=True)),
                ('vasprun', models.TextField(null=True)),
                ('xdatcar', models.TextField(null=True)),
                ('wavecar', models.TextField(null=True)),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('mod_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
